### ISSUE TITLE
Comic Rocket script

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/GreasemonkeyScripts#6]
#### TODO
- [x] Post this issue in various [UserVoice threads](https://comicrocket.uservoice.com/forums/70859-general) to get feedback from the community.
##### Sorting
- [x] Title
- [x] Rating
- [x] Unread Pages
- [x] Read Pages
- [x] Total Pages
- [x] Percent Read
- [x] Updated Date
- [ ] Date of last access
##### Filtering
- [x] Search within your comics by title
- [x] Show/hide comics by rating
- [x] Show overall progress in sidebar
- [ ] Show/hide by custom tags
- [ ] Show/hide broken comics
- [ ] Show/hide unindexed comics
- [ ] Hide comics with only 1 read page
- [ ] Hide comics with all pages read
##### Styles/Layout
- [ ] Show/hide sidebar
- [ ] Show/hide cover images
- [ ] Put comics into two columns (with sidebar) or three (without sidebar)
- [ ] Paginate comic list
- [ ] Table view for comics that strips cruft and leaves basic comic info in place
- [ ] Tag cloud in sidebar
##### Tagging/Metadata
- [ ] Add custom tags to comics
- [ ] Custom quality ratings for each comic (e.g. "3/5 stars")
- [ ] More granular [content ratings](https://en.wikipedia.org/wiki/TV_Parental_Guidelines#Content_descriptors) for each comic
- [ ] Allow for excluding one or more tags from overall progress count
##### Other
- [ ] Use local storage to persist state for sorting, possibly other settings
- [ ] Customize comic viewer with support for arrow keys, swiping, and large clickable area for navigating back and forth (good for mobile users)
- [ ] Manually set number of pages read
##### Bugs in/Changes to current functionality
- [x] No Rating is not sorted properly. It seems to just put them [wherever](http://i.imgur.com/5nwo4QK.png).
- [ ] Leave broken and unindexed comics at the bottom of the page, or even optionally hide them altogether by default.

**Comment by chimericdream** [comment]
Related UserVoice threads:

https://comicrocket.uservoice.com/forums/70859-general/suggestions/979051-let-me-group-the-serials-on-my-user-page
https://comicrocket.uservoice.com/forums/70859-general/suggestions/3064815-allow-a-sorting-feature-to-my-comics
https://comicrocket.uservoice.com/forums/70859-general/suggestions/3906652-personal-rating

**Comment by chimericdream** [comment]
#### TODO

 * [ ] Post this issue in various [UserVoice threads](https://comicrocket.uservoice.com/forums/70859-general) to get feedback from the community.

**Comment by Efreak** [comment]
As a user with 389 tracked comics, this seems to work fine at a first glance. I do have some extra ideas, though. The later ones get rather advanced and are probably unnecessary, but somehow I don't think that comic rocket has any interest at all in improving their service or app for users.

###### Bug:
1. _No Rating_ is not sorted properly. It seems to just put them [wherever](http://i.imgur.com/5nwo4QK.png).
2. Leave broken and unindexed comics at the bottom of the page, or even optionally hide them altogether by default. I've got several dozen comics down there below all those with pages TBR, and [they show up in the sorted list](http://i.imgur.com/JKI18Kx.png). I don't want to remove them because I still read them.

###### New Sorts/filters
1. Unread count (_`var r1 = parseInt(a.attr('data-read')) - parseInt(a.attr('data-total'))`_)
2. Percent read (_`var r1 = parseInt(a.attr('data-read')) / parseInt(a.attr('data-total'))`_)
3. Date of last access, and date of last viewing. This would probably have to wait for local storage implementation. Probably just set the current date on new comics (ie, comics that were added from another computer), and any time a comic gets clicked. Once implemented, ability to hide comics if this date is <24h old.
4. Add _no rating_ to the filter, and use checkboxes, not radio buttons - I should be able to show PG+Unrated, but not NC-17 and R.
5. hide only 1 page read (comic-rocket doesn't allow you to add a comic without marking the first page read, so this is how I set them as 'to be read')
6. hide all pages read (this is more useful than last updated when sorted by unread pages)

###### New stuff
1. Options to restyle the page
   - dump the sidebar and put comics in more than one column, with size options  - [css](https://gist.github.com/5e403f6cffd4c1fd49077288523e821b), and a [screenshot](http://i.imgur.com/9m6EZiH.png) at 60% zoom on .comics-item to reduce item size.
   - hide cover images (_`div.comics-item-body > a > img { display:none;}`_)
   - table view (for when we don't care about who else is reading it and don't need to see images; I didn't implement this)
2. If possible, it would also be nice to have a scripted viewer with (optional) support for arrow keys, swiping, and large forward/next buttons (or clickable margins) - I've been planning this anyways, as I have issues with the mobile client crashing multiple times during long sessions, and I don't like using the mouse when reading comics (I tend to write short userscripts for browsing on the desktop). The [bookmarklets](https://www.comic-rocket.com/help/bookmarklets/) may help with this.
3. Not sure if comic rocket's api supports this, but it would be nice to be able to manually set the number of read pages, especially for broken comics.

**Comment by chimericdream** [comment]
@Efreak Thanks for the awesome feedback! This is more than I hoped for when I spammed the UserVoice threads (something I felt a _little_ dirty for, but am now glad I did).

> ###### Bug:
> 1. _No Rating_ is not sorted properly. It seems to just put them [wherever](http://i.imgur.com/5nwo4QK.png).
> 2. Leave broken and unindexed comics at the bottom of the page, or even optionally hide them altogether by default. I've got several dozen comics down there below all those with pages TBR, and [they show up in the sorted list](http://i.imgur.com/JKI18Kx.png). I don't want to remove them because I still read them.

Thanks for these. I'll make sure to add some of the comics in your screenshots to my test account (which has ~250 comics I added at random). If you have suggestions for more broken/no rating/unindexed comics I can add to improve my testing, I'd love to have more to test with.

> ###### New Sorts/filters
> 1. Unread count (_`var r1 = parseInt(a.attr('data-read')) - parseInt(a.attr('data-total'))`_)
> 2. Percent read (_`var r1 = parseInt(a.attr('data-read')) / parseInt(a.attr('data-total'))`_)
> 3. Date of last access, and date of last viewing. This would probably have to wait for local storage implementation. Probably just set the current date on new comics (ie, comics that were added from another computer), and any time a comic gets clicked. Once implemented, ability to hide comics if this date is <24h old.
> 4. Add _no rating_ to the filter, and use checkboxes, not radio buttons - I should be able to show PG+Unrated, but not NC-17 and R.
> 5. hide only 1 page read (comic-rocket doesn't allow you to add a comic without marking the first page read, so this is how I set them as 'to be read')
> 6. hide all pages read (this is more useful than last updated when sorted by unread pages)

I love all of these. I wholeheartedly agree with number 4 and had come to the same conclusion yesterday when I wanted to hide _just_ NC-17 from my list at work. Number 3, as you mentioned, will likely wait until I implement local storage in the script, but I like the idea.

> ###### New stuff
> 1. Options to restyle the page
>    - dump the sidebar and put comics in more than one column, with size options  - [css](https://gist.github.com/5e403f6cffd4c1fd49077288523e821b), and a [screenshot](http://i.imgur.com/9m6EZiH.png) at 60% zoom on .comics-item to reduce item size.
>    - hide cover images (_`div.comics-item-body > a > img { display:none;}`_)
>    - table view (for when we don't care about who else is reading it and don't need to see images; I didn't implement this)
> 2. If possible, it would also be nice to have a scripted viewer with (optional) support for arrow keys, swiping, and large forward/next buttons (or clickable margins) - I've been planning this anyways, as I have issues with the mobile client crashing multiple times during long sessions, and I don't like using the mouse when reading comics (I tend to write short userscripts for browsing on the desktop). The [bookmarklets](https://www.comic-rocket.com/help/bookmarklets/) may help with this.
> 3. Not sure if comic rocket's api supports this, but it would be nice to be able to manually set the number of read pages, especially for broken comics.

I definitely like the idea of being able to customize the styles, especially for users who have hundreds of comics. Number 2 seems like something that should be doable, in some fashion at least. For number 3, I like the idea and will have to think about possible ways to accomplish the goal.

**Comment by Efreak** [comment]
I considered spamming the UserVoice threads, but it seems to me that Comic Rocket isn't interested in developing the service at all anymore. They seem to feel that they're done, even with the terrible android app (it crashes on me every ~50 pages and [has](https://play.google.com/store/apps/details?id=com.comicrocket.androidapp) apparently [been](https://play.google.com/store/apps/developer?id=Comic+Rocket&hl=en) taken [down](https://play.google.com/store/search?q=comic+rocket&c=apps), and according to reviews, the [ios app](https://itunes.apple.com/us/app/comicrocket/id936292170?mt=8) is/was even worse). Given all that, I felt they'd probably just ignore my comments there (as they seem to be doing to everyone else). They seem to feel that the service is complete, finished, and that there's nothing left to do except tell people they can't index scripted comics and comics that don't have traditional button layouts.

If tampermonkey evers gets itself working on firefox mobile, I'll probably be using this fairly often.
